@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(employee, "Сотрудник", "Формулирует цели, создает, редактирует и отслеживает планы развития")
Person(mentor, "Наставник", "Редактирует планы, дает рекомендации, отслеживает прогресс")
Person(director, "Директор", "Получает отчеты и анализирует их")

System(system, " Система для управления планами развития сотрудников", "Централизованная система для формирования, согласования и мониторинга планов развития сотрудников, а также измерения компетенций")

System_Ext(reporting, "Внешняя система отчётности", "Существующие инструменты отчётности с выгрузкой в Excel")

Rel(employee, system, "Создаёт и редактирует планы, отслеживает прогресс")
Rel(mentor, system, "Редактирует планы, оставляет комментарии, оценивает компетенции")
Rel(director, system, "Просматривает отчёты и отслеживает метрики")
Rel(system, reporting, "Выгружает данные о прогрессе и компетенциях вместе с другими данными о сотруднике", "Excel")

@enduml
