name: Docker CI with Newman

on:
  push:
    branches: LabWork5
  pull_request:
    branches: LabWork5


jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing volumes
        run: docker compose down -v

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run Postman tests
        run: docker compose run --rm tests

      - name: Stop containers
        if: always()
        run: docker compose down -v